pipeline {
    agent none

    stages {
        stage('SCA Analysis') {
            // agent {
            //     docker {
            //         image 'python:3.10.12-slim-bookworm'
            //         args '--network host -u root:root'
            //     }
                
            // }
            agent any

            environment {
                SCA_API_URL = 'http://54.158.47.114:8000/api/results/'
                SCA_API_TOKEN = credentials('SCA_API_TOKEN')
            }

            steps {
                sh 'docker run -it -v ${{PWD}}:/src ghcr.io/google/osv-scanner --format markdown -L /src/requirements.txt > sca_result.md'
                sh 'pip install requests'
                sh '''python3 cicd/scripts/sca/main.py -L requirements.txt \
	                            -i ${GIT_COMMIT} \
	                            -b ${GIT_BRANCH} -u usr${BUILD_NUMBER}@mail.com \
	                            -a $SCA_API_URL \
	                            -t $SCA_API_TOKEN
                '''
            }
        }
    }
}