# Generated by Django 4.1.13 on 2024-01-14 12:42

from django.db import migrations, models
import djongo.models.fields
import sca.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('osv_url', models.TextField(primary_key=True, serialize=False)),
                ('cvss', models.CharField(max_length=4)),
                ('ecosystem', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerabilities', djongo.models.fields.ArrayField(model_container=sca.models.Vulnerability)),
                ('execution_id', models.CharField(max_length=100)),
                ('git_branch', models.CharField(max_length=100)),
                ('git_user', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
